# Generated by Django 2.1.7 on 2019-03-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190308_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindhost',
            name='remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.RemoteUser'),
        ),
    ]
